### ISSUE TITLE
Finding the reference sites

### ISSUE THREAD

**Issue by Eun-Min** [Eun-Min/OpenKCsauce#7]
Finding the reference sites about RPG using C.

**Comment by Eun-Min** [comment]
http://m.blog.naver.com/pop9719/30106165878

**Comment by kimDDong** [comment]
http://proordin.tistory.com/entry/C-C-%EC%96%B8%EC%96%B4-RPG-TEXT-WORLD

**Comment by kimDDong** [comment]
http://codereview.stackexchange.com/questions/80531/c-text-based-rpg

**Comment by kimDDong** [comment]
http://cboard.cprogramming.com/game-programming/119463-text-based-rpg.html

**Comment by young6900** [comment]
http://codereview.stackexchange.com/questions/27986/text-based-rpg-game-using-classes
